# scripts/pipeline/05_define_fsf_signatures_all.R
# Purpose: Identify shared top markers between dataset pairs and validate on the third dataset.
#          Runs all reviewer directions:
#            - A×B validate C
#            - A×C validate B
#            - B×C validate A
# Inputs (from results/tables/ generated by processing scripts):
#   - top10_salvador_macrophage_clusters.csv
#   - top10_milich_macrophage_clusters.csv
#   - top10_brennan_macrophage_clusters.csv
#   - top10_logfc_salvador_macrophage_clusters.csv
#   - top10_logfc_milich_macrophage_clusters.csv
#   - top10_logfc_brennan_macrophage_clusters.csv
# Outputs (written to results/tables/fsf_signatures/):
#   - shared_AB_pvalue.csv, shared_ABC_pvalue.csv
#   - shared_AC_pvalue.csv, shared_ACB_pvalue.csv
#   - shared_BC_pvalue.csv, shared_BCA_pvalue.csv
#   - shared_AB_logfc.csv,  shared_ABC_logfc.csv
#   - shared_AC_logfc.csv,  shared_ACB_logfc.csv
#   - shared_BC_logfc.csv,  shared_BCA_logfc.csv

source("scripts/pipeline/00_config.R")

suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
})

out_dir <- file.path(DIR_TABLES, "fsf_signatures")
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

# ------------------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------------------

shared_between_two <- function(df1, df2, suffix1, suffix2) {
  intersect_genes <- intersect(df1$gene, df2$gene)
  
  df1_common <- df1 %>% filter(gene %in% intersect_genes)
  df2_common <- df2 %>% filter(gene %in% intersect_genes)
  
  shared <- merge(
    df1_common, df2_common,
    by = "gene",
    suffixes = c(paste0("_", suffix1), paste0("_", suffix2))
  )
  
  shared %>%
    select(
      gene,
      starts_with("cluster"),
      starts_with("p_val_adj"),
      starts_with("avg_log2FC")
    ) %>%
    arrange(.data[[paste0("cluster_", suffix1)]])
}

validate_on_third <- function(shared_df, df3, suffix3) {
  df3_common <- df3 %>% dplyr::filter(gene %in% shared_df$gene)
  
  merged <- merge(shared_df, df3_common, by = "gene")
  
  # rename df3 columns safely without using :=
  rename_map <- c(
    cluster   = paste0("cluster_", suffix3),
    p_val_adj = paste0("p_val_adj_", suffix3),
    avg_log2FC = paste0("avg_log2FC_", suffix3)
  )
  
  for (old in names(rename_map)) {
    if (old %in% names(merged)) {
      names(merged)[names(merged) == old] <- rename_map[[old]]
    }
  }
  
  merged %>%
    dplyr::select(
      gene,
      dplyr::starts_with("cluster"),
      dplyr::starts_with("p_val_adj"),
      dplyr::starts_with("avg_log2FC")
    ) %>%
    dplyr::mutate(dplyr::across(dplyr::starts_with("avg_log2FC"), ~ round(.x, 2)))
}


run_pair_validation <- function(dfA, dfB, dfC,
                                labA = "A", labB = "B", labC = "C",
                                nameA = "salvador", nameB = "milich", nameC = "brennan",
                                flavor = c("pvalue", "logfc")) {
  flavor <- match.arg(flavor)
  
  pair_code <- paste0(substr(labA, 1, 1), substr(labB, 1, 1))  # AB, AC, BC
  triple_code <- paste0(pair_code, substr(labC, 1, 1))         # ABC, ACB, BCA
  
  shared_AB <- shared_between_two(dfA, dfB, suffix1 = nameA, suffix2 = nameB)
  write_csv(shared_AB, file.path(out_dir, paste0("shared_", pair_code, "_", flavor, ".csv")))
  
  shared_ABC <- validate_on_third(shared_AB, dfC, suffix3 = nameC)
  write_csv(shared_ABC, file.path(out_dir, paste0("shared_", triple_code, "_", flavor, ".csv")))
  
  invisible(list(shared_pair = shared_AB, shared_validated = shared_ABC))
}

# ------------------------------------------------------------------------------
# Load inputs
# ------------------------------------------------------------------------------
# pvalue-top10
A_p <- read_csv(file.path(DIR_TABLES, "top10_salvador_macrophage_clusters.csv"), show_col_types = FALSE) 
B_p <- read_csv(file.path(DIR_TABLES, "top10_milich_macrophage_clusters.csv"), show_col_types = FALSE) 
C_p <- read_csv(file.path(DIR_TABLES, "top10_brennan_macrophage_clusters.csv"), show_col_types = FALSE) 

# logFC-top10
A_l <- read_csv(file.path(DIR_TABLES, "top10_logfc_salvador_macrophage_clusters.csv"), show_col_types = FALSE) 
B_l <- read_csv(file.path(DIR_TABLES, "top10_logfc_milich_macrophage_clusters.csv"), show_col_types = FALSE) 
C_l <- read_csv(file.path(DIR_TABLES, "top10_logfc_brennan_macrophage_clusters.csv"), show_col_types = FALSE)

# ------------------------------------------------------------------------------
# Run all three reviewer directions
# ------------------------------------------------------------------------------
# A×B validate C
run_pair_validation(A_p, B_p, C_p, labA="A", labB="B", labC="C", nameA="salvador", nameB="milich", nameC="brennan", flavor="pvalue")
run_pair_validation(A_l, B_l, C_l, labA="A", labB="B", labC="C", nameA="salvador", nameB="milich", nameC="brennan", flavor="logfc")

# A×C validate B
run_pair_validation(A_p, C_p, B_p, labA="A", labB="C", labC="B", nameA="salvador", nameB="brennan", nameC="milich", flavor="pvalue")
run_pair_validation(A_l, C_l, B_l, labA="A", labB="C", labC="B", nameA="salvador", nameB="brennan", nameC="milich", flavor="logfc")

# B×C validate A
run_pair_validation(B_p, C_p, A_p, labA="B", labB="C", labC="A", nameA="milich", nameB="brennan", nameC="salvador", flavor="pvalue")
run_pair_validation(B_l, C_l, A_l, labA="B", labB="C", labC="A", nameA="milich", nameB="brennan", nameC="salvador", flavor="logfc")

message("✅ FSF signature tables written to: ", out_dir)
